### ISSUE TITLE
LMNTAL_HOMEを設定していない状態でGrapheneを呼び出すとエラーになる

### ISSUE THREAD

**Issue by nikosai** [lmntal/lavit#40]
環境変数 `LMNTAL_HOME` を適切に設定していない状態で、LaViT上からGrapheneを呼び出した場合、setPropertyまわりでNullPointerExceptionが起きる。

~~（Mac特有？）~~ WSL（Ubuntu18.04）でも再現

**Comment by nikosai** [comment]
Grapheneの以下の場所で環境変数 `LMNTAL_HOME` をもとにデフォルトのslimpathを作っているのが原因らしい
https://github.com/lmntal/Graphene/blob/ca08cab2c656a966b0fd184614b9a67587a7a22e/src/main/scala/graphene/plugin/lmntal/LMNtal.scala#L64-L65

**Comment by nikosai** [comment]
関連： #32

**Comment by k-ueda** [comment]
WSL2 w/GUI (Ubuntu 22.04LTS) でも再現しました．
